### ISSUE TITLE
Does Voltaire use its own mempool of UserOperations or does it used a shared mempool?

### ISSUE THREAD

**Issue by reselbob** [candidelabs/voltaire#10]
Hi:

I am researching Voltaire. As I ask in the title, does Voltaire use its own mempool of UserOperations or does it used a shared mempool?

If it does use its own mempool, how and where does that mempool run?

If it shares a mempool, where is that mempool?

Thanks in advance for any help you can provide.

**Comment by sherifahmed990** [comment]
Hello Bob,

Right now the shared mempool is only in Sepolia and is under active development, for other chains you can use Voltaire as a private bundler.

You can use the following command to join the shared mempool in Sepolia

docker run --name sepolia-p2p --net=host -v voltaire-p2p-1:/app/cache --rm ghcr.io/candidelabs/voltaire/voltaire-bundler:latest --bundler_secret $BUNDLER_SECRET --chain_id 11155111 --verbose --bundle_interval 15 --ethereum_node_url $NODE_RPC --p2p_boot_nodes_enr enr:-KS4QDzM0KpTtthqpLEX5IaNosqSQWVU1haboFx0bZCDm8xHNgGNG7xCiXD-S1Dewicw7wPcGrO7tkkWxKs0_WLe8SoBgmlkgnY0gmlwhDMU_A2PbWVtcG9vbF9zdWJuZXRziAAAAAAAAAAAiXNlY3AyNTZrMaEC0iIcpRYZU3l_Kw7DccVgU9-ISVw551wsyw7iqpZwpImDdGNwgiMog3VkcIIjKA

**Comment by reselbob** [comment]
So, just so I understand clearly, the concept of shared alt-mempool is not unusual, but that at the production level the various projects using Voltaire are using their own alt-mempool. True?

Also, is there any way to view the alt-mempool on Sepolia? (Also, operationally, it looks as if I need to create a Bundler secret on my end and assign it to the environment variable `$BUNDLER_SECRET`. Might there be documentation the describes how to create and use a bundler secret for Voltaire.)

Thanks for the previous response. It means a lot to me that you responded so quickly.

**Comment by sherifahmed990** [comment]
You are welcome

Bundlers in production currently are private bundlers, each bundler has it's own local/private mempool.

Bundlers can communicate with each other using the libp2p protocol and share useroperations creating a "shared mempool".

Bundlers need to validate useroperations before sharing them with other bundlers, each mempool has it's own set of validtion rules, the mempool with the default rules set (see erc-7562) is the "canonical mempool".

Any other mempools with different/relaxed set of rules are called "alt-mempools".

**Comment by sherifahmed990** [comment]
You can check the contents of each bundler mempool using the  json-rpc api method "debug_bundler_dumpMempool", debug mood needs to be enabled for the bundler to access this api method.

**Comment by reselbob** [comment]
Again, thank you, sincerely.
