### ISSUE TITLE
Exclude Empty null Fields from Triggering Invalid UserOperation Errors

### ISSUE THREAD

**Issue by Sednaoui** [candidelabs/voltaire#18]
When processing a `UserOperation` object, fields that are not included—specifically the Paymaster fields—should not trigger an `invalid UserOperation` error. Since these fields can set to `null`, they should be considered optional and their absence should not cause the operation to return invalid userop.

**Comment by sherifahmed990** [comment]
00b6581a4d09a640f12686f02b30653eddbe4dec
