### ISSUE TITLE
ETHEREUM_NODE_URL vs RPC_URL

### ISSUE THREAD

**Issue by willpiam** [candidelabs/voltaire#7]
What are the two fields for and how are they different?

**Comment by Sednaoui** [comment]
`--ethereum_node_url` is the url to the of your node endpoint 

`--rpc_url` is the url of the endpoint you will be hosting. Default is `0.0.0.0` but you can use anything you want like `127.0.0.1`

Once it's hosted, you can send requests to your bundler to `0.0.0.0:3000/rpc` with 3000 as your default port

**Comment by willpiam** [comment]
Perfect thank you!
