### ISSUE TITLE
implement a health-check endpoint

### ISSUE THREAD

**Issue by ayazabbas** [candidelabs/voltaire#8]
A `/health` endpoint that returns 200 is useful to verify the http server is up and reachable. Maybe there are some useful checks that could also be included here?

**Comment by sherifahmed990** [comment]
The --metrics flag will enable prometheus metrics at port 8000, the "up" health metric can be collected from the prometheus client.
For now it has some basic metrics for cpu and memory usage, and the number of requests served for each rpc method.
Also we plan to create a Grafana dashboard.
Let me know if you have any suggestions for metrics to be added.

**Comment by ayazabbas** [comment]
That is very useful to know, thanks!

I am thinking about how to run the bundler in a durable fashion, with multiple instances, and a http status endpoint is kind of necessary for load-balancer healthchecks.

**Comment by sherifahmed990** [comment]
That makes sense, i will add the /health endpoint.

**Comment by sherifahmed990** [comment]
A basic /health endpoint d3f9286cf48ff265ad4871b1e7689581f423b069

**Comment by itxtoledo** [comment]
> A basic /health endpoint [d3f9286](https://github.com/candidelabs/voltaire/commit/d3f9286cf48ff265ad4871b1e7689581f423b069)

Most hosting companies expect /health to be a GET request, not a POST request; for example, that's how it works on Railway.
